repos:
#  - repo: local
#    hooks:
#      - id: jupyter-nb-clear-output
#        name: jupyter-nb-clear-output
#        language: system
#        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout
        files: \.ipynb$
        stages: [ pre-commit ]

  - repo: https://github.com/jendrikseipp/vulture
    rev: 'v2.10'
    hooks:
      - id: vulture
        args: [
          "--min-confidence", "80",
          "app"  # project_name - path to scan
        ]
        files: ^.*\.py$
        exclude: ^(.git|.venv|venv|build|dist)/.*$

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        args: [
          "--cov=app",  # project_name - path to scan
          "--cov-report=xml",
          "--cov-fail-under=50",
        ]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.0
    hooks:
      - id: pyupgrade

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.399
    hooks:
      - id: pyright
        additional_dependencies: ["pyright==1.1.399"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.7.4
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [ python, pyi ]
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi ]
